[package]
name = "hamesh_cli"
version = "0.3.0"
edition = "2021"


[[bin]]
name = "hamesh_cli"
path = "src/main.rs"

[dependencies]
hamesh = {path = "../core"}
regex = "1.10.3"
simple_logger = "4.3.3"
log = "0.4.20"
tokio = { version = "1.27", features = ["full"] }